print('Murilo', type('Murilo'))
print(10, type(10))
print(25.23, type(25.23))
print(10 == 10, type(10 == 10))
print('l' == 'L', type('l' == 'L'))
print(bool('[])'))
print(type('Murilo'), bool('Murilo'))